# Introduction


I started this project with the goal of answering this question: "if you take a character in a novel and replace all direct references to their gender such as pronouns with gender-neutral alternatives, how accurately could you predict their gender?"

The steps required to answer this question led to even more questions, and this project’s scope has grown to include examinations of author and genre bias. 

Gendered stereotypes influence behavior. The embodied approach to cognition views cognition as grounded in the body, so socially imposed perceptions of body might shape gendered behavior [@Lee2016]. While writing a novel, an author might image the perspective of their characters. By embodying a character, the author’s cognition becomes grounded in an imaged body and their writing might reflect their interpretation of the body.

 The interpretation and generalizing of gender differences risks perpetuating stereotypes and gender essentialism [@Koolen2017]. Examining gender differences in fictional characters provides an opportunity to explore gender stereotypes and examine some of variables confounding the interpretation of lexical differences between male and female authors.
 
Viewing gender through the lens of performativity can sometimes be intepreted to invalidate self-determined queer and trans identities, but TERFS can fuck off [@Finlay2017].
