# Methods

## Book corpus

This study used 6,462 of the 10,000 most popular books listed on goodreads.com [@goodbooks-10k].

Author gender was estimated using baby name popularity from 20-60 years prior to publication date [@SocialSecurity]. When multiple authors were listed, the first author's name was used. I manually annotated the most common authors whose first name was not listed in the database. This method doesn't account for ghost writers, pen names, multiple authors, writers born outside the United States, or name-gender discrepancies (for example, a person named "Russell" could be non-binary). To estimate this method's accuracy, I manually reviewed 100 entries and found 2 incorrectly gendered authors.

Gender is not binary, and binary classification of author gender is only a convenient approximation.

## Natural language processing

Lemmatization and part-of-speech tagging was performed with Spacy [@spacy2], and character coreferences were resolved with NeuralCoref [@NeuralCoref].

Individual characters were defined as entities with 25 or more coreferenced pronouns. Character gender was determined by pronoun usage.

For each character, a bags-of-word was extracted for each sentence where they were referenced.

## Differential expression

The assumptions required to compare bags-of-words are remarkably similar to those in analyzing differential expression of next-gen RNA sequencing data. I took advantage of this by using DESeq2 [@DESeq2] to apply generalized linear models with a negative binomial distribution to estimate differences in word frequency between male and female characters and authors.
